# Haskell stack project Github Actions template
# based on: https://gist.github.com/mstksg/11f753d891cee5980326a8ea8c865233

name: Haskell Stack Project CI

on:
  push:
  schedule:
  - cron: "0 0 * * 1"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        # use this to specify what resolvers and ghc to use
        plan:        
        - { build: stack, resolver: "--resolver lts-14.21"  }   # ghc-8.6.5       
        include: []
        # - os: macOS-latest
        #   brew: anybrewdeps
        # - os: ubuntu-latest
        #   apt-get: happy libblas-dev liblapack-dev
      

    runs-on: ${{ matrix.os }}
    steps:
    - name: Install OS Packages
      uses: mstksg/get-package@v1
      with:
        apt-get: ${{ matrix.apt-get }}
        brew: ${{ matrix.brew }}
    - uses: actions/checkout@v1

    - name: Setup stack
      uses: mstksg/setup-stack@v1   

    - name: Install dependencies
      run: |
        set -ex
        case "$BUILD" in
          stack)
            stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
            ;;         
        esac
        set +ex
      env:
        ARGS: ${{ matrix.plan.resolver }}
        BUILD: ${{ matrix.plan.build }}

    - name: Build
      run: |
        set -ex
        case "$BUILD" in
          stack)
            stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
            ;;         
        esac
        set +ex
      env:
        ARGS: ${{ matrix.plan.resolver }}
        BUILD: ${{ matrix.plan.build }}
